config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Resque::Server.new, at: "/resque"

  get '/login' => 'auth#new'
  post '/login' => 'auth#create'
  get '/logout' => 'auth#destroy'

  root 'cast#index'
  get 'cast/index'
  get 'cast/about'

  get 'display/select'
  post 'display/select'
  get 'display/index'
  get 'display/current'

  get 'upload/index'
  post 'upload/index'
  post 'upload/uploadFile'

  get 'operator/index'
  get 'operator/select'
  post 'operator/select'
  post 'operator/pushTextSeq'
  post 'operator/pushBlackout'

  post 'texts/toggleVis'

  resources :works, only: [:index, :edit, :destroy, :update] do
    resources :texts, except: [:show]
  end

end

app/controllers/display_controller.rb
class DisplayController < ApplicationController
  def index
    @operator = params[:operator]

    #vend all lines out to the display view
    @jtext=Text.all.where(work: params[:work]).to_json(:include => :element);

    #pick between multi-line view and single line with a parameter
    if params[:view] == "multi"
      render "multi"
    elsif params[:view] == "single"
      render "index"
    end
  end

  def current
    blackout_redis_key = "operator_" << params[:operator] << "_blackout"
    sequence_redis_key = "operator_" << params[:operator] << "_sequence"
    blackout = DataCache.data.get(blackout_redis_key)
    text_sequence = DataCache.data.get(sequence_redis_key)
    render json: {:pos => text_sequence, :blackout => blackout}
  end

  def select

    if request.get?
      @operators = Operator.all
    end

    if request.post?
      operator = Operator.find_by(id: params[:selected_operator])
      view = operator.view_attributes
      work = Work.find_by(id: operator.work_id)

      redirect_to :controller => 'display', :action => 'index', :view => view,
        :work => work, :operator => operator
    end
  end

end

app/helpers/display_helper.rb
module DisplayHelper
end

app/views/display/index.html.erb
<div class="container-fluid" id="main-display">

<div class="row" id="row-display">
  <div class="col-lg-12 col-xs-12" id="line-holder-display">
  	<div class="line-display" id="line-display-0" data-sequence="0">
      <span class="line-full-display">
        <span class="line-char-display"></span>
        <span class="line-content-display"></span>
      </span>
    </div>
    <!-- rest of the lines go here -->
  </div>
</div>
</div>

<div id="shade-single"></div>
<div id="shade-loading-display">The script is now loading...</div>

<%= render "shared/js_global_injection" %>

app/views/display/multi.html.erb
<div id="multi-flag-display" style="display:none"></div>

<div class="container-fluid" id="main-display">
  <div class="row" id="row-display-multi">
    <div id="buffer-top-display-multi"></div>
    <div class="col-lg-12 col-xs-12" id="line-holder-display-multi">
      <div class="line-display-multi" id="line-display-0" data-sequence="0">
      	<span class="line-full-display">
      		<span class="line-char-display"></span>
      		<span class="line-content-display"><br></span>
      	</span>
      </div>
    </div>
    <div id="buffer-bottom-display-multi"></div>
  </div>
</div>

<div id="shade-multi"></div>
<div id="shade-loading-display">The script is now loading...</div>

<%= javascript_tag do %>
  var operator= '<%=@operator%>'
<%end%>

<%= render "shared/js_global_injection" %>

app/views/display/select.html.erb
<div class="container" id="main-upload">
  <div id="display-select-wrapper" class="col-xs-12 col-sm-12 col-md-8 col-md-push-2 col-lg-6 col-lg-push-3">
    <%= content_tag :div, :id=>"main-form-upload", :class=>"row" do %>

        <span id="title-display">Select An Operator</span>
        <div id="select_display_op">
            <% @operators.each do |operator| %>
            <% work = Work.find_by(id: operator.work_id) %>
            <% venue = work.venue %>
            <%= link_to "#{operator.name} | #{work.name}", display_select_path(:selected_operator =>operator.id), method: :post%>
            </br>
          <% end %>
        </div>

    <% end %>
  </div>
</div>