config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Resque::Server.new, at: "/resque"

  get '/login' => 'auth#new'
  post '/login' => 'auth#create'
  get '/logout' => 'auth#destroy'

  root 'cast#index'
  get 'cast/index'
  get 'cast/about'

  get 'display/select'
  post 'display/select'
  get 'display/index'
  get 'display/current'

  get 'upload/index'
  post 'upload/index'
  post 'upload/uploadFile'

  get 'operator/index'
  get 'operator/select'
  post 'operator/select'
  post 'operator/pushTextSeq'
  post 'operator/pushBlackout'

  post 'texts/toggleVis'

  resources :works, only: [:index, :edit, :destroy, :update] do
    resources :texts, except: [:show]
  end

end

app/models/work.rb
class Work < ActiveRecord::Base
  belongs_to :venue
  has_many :texts, -> { order "sequence" }
  has_many :elements

  validates_presence_of :work_name
  validates_presence_of :venue_id
  validates_presence_of :language

  #places the name/language in the dropdown for selecting the script to edit
  def name
    "#{work_name}. #{language}"
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController

  before_filter :authorize

  def index
    @works = Work.order(:work_name, :language)
  end

  def edit
    @work = Work.find_by_id(params[:id])
  end

  def destroy
    Operator.delete_all(:work_id => params[:id])
    Text.delete_all(:work_id => params[:id])
    Element.delete_all(:work_id => params[:id])
    Work.find_by_id(params[:id]).delete
    redirect_to :controller => 'cast', :action => 'index'
  end

  def update
    @work = Work.find_by_id(params[:id])
    @work.update(params.require(:work).permit(:work_name))
    redirect_to :controller => 'cast', :action => 'index'
  end

  private

  # used for bringing in params sent to the create function
  def message_params
    params.require(:text).permit(:content_text)
  end

end

app/helpers/works_helper.rb
module WorksHelper
  def work_details(work)
    string = "#{work.work_name}: #{work.language}"
    string += " (#{pluralize(work.texts.count, 'text')})" if not work.texts.empty?
    string
  end
end

app/views/works/edit.html.erb
<div class="container" id="main-upload">
  <span class="glyphicon glyphicon-cog pull-right"></span>
  <h2>Settings for <%= @work.name %></h2>
  <hr />
  <%= form_for @work do |f| %>
    <fieldset class="form-group">
      <label>Work Name: </label>
      <%= f.text_field :work_name, :class => "form-control" %>
    </fieldset>
    <!-- form is already set up to update all the attributes of the work.
           just add more fields to this form. -->
    <%= f.submit nil, :class => "btn btn-primary" %>
  <% end %>

  <h2 class="form-title delete_item">Danger</h2>
  <hr />
  <%= link_to "Delete", work_path(@work.id),
    data: { confirm: "Are you sure you want to delete #{@work.name.upcase}?" },
    class: "btn btn-danger", method: "delete" %>
</div>

app/views/works/index.html.erb
<div class="container" id="main-work">
    <div id="work-wrapper" class="col-xs-12 col-sm-12 col-md-8 col-md-push-2 col-lg-6 col-lg-push-3">
        <span id="title-work">Select a script to edit</span>
        <% if @works.blank? %>
            <p>No works to display.</p>
        <% else %>
            <ul id="works" class="list-group">
                <% @works.each do |work| %>
                    <li class="list-group-item">
                        <% if work.upload_status == "Uploading" %>
                            <%= work_details(work) %>
                            <span class="label label-warning label-pill pull-right">
                                Uploading
                            </span>
                        <% elsif work.upload_status == "Failed" or work.texts.empty? %>
                            <%= work_details(work) %>
                            <span class="pull-right">
                                <%= button_to edit_work_path(work.id), class: "btn btn-xs btn-primary", method: "get" do %>
                                    Settings
                                <% end %>
                            </span>
                            <span style="margin-right: 10px;" class="label label-danger label-pill pull-right">
                                Upload Failed 
                            </span>
                        <% elsif work.upload_status == "Ready" %>
                            <%= link_to work_details(work), work_texts_path(work.id) %>
                            <span class="pull-right">
                                <%= button_to edit_work_path(work.id), class: "btn btn-xs btn-primary", method: "get" do %>
                                    Settings
                                <% end %>
                            </span>
                        <% end %>
                    </li>
                <% end %>
            </ul>
        <% end %>
    </div>
</div>