config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Resque::Server.new, at: "/resque"

  get '/login' => 'auth#new'
  post '/login' => 'auth#create'
  get '/logout' => 'auth#destroy'

  root 'cast#index'
  get 'cast/index'
  get 'cast/about'

  get 'display/select'
  post 'display/select'
  get 'display/index'
  get 'display/current'

  get 'upload/index'
  post 'upload/index'
  post 'upload/uploadFile'

  get 'operator/index'
  get 'operator/select'
  post 'operator/select'
  post 'operator/pushTextSeq'
  post 'operator/pushBlackout'

  post 'texts/toggleVis'

  resources :works, only: [:index, :edit, :destroy, :update] do
    resources :texts, except: [:show]
  end

end

app/models/text.rb
class Text < ActiveRecord::Base
  belongs_to :work
  belongs_to :element
  validates_presence_of :work_id
  validates_presence_of :element_id
  validates_presence_of :sequence
  validates_presence_of :content_text

  delegate :element_name, to: :element
  delegate :element_type, to: :element

  acts_as_list scope: :work, column: :sequence 

  def previous_display_text(work, sequence)
    previous_text = work.texts.find_by sequence: sequence - 1
    if previous_text.nil?
      "Start of Script"
    else
      previous_text.display_string
    end
  end

  def next_display_text(work_id, sequence)
    next_text = work.texts.find_by sequence: sequence + 1
    if next_text.nil?
      "End of Script"
    else
      next_text.display_string
    end
  end

  def display_string
    "#{self.element.name}: #{self.content_text unless self.element.name == "BLANKLINE"}"
  end

end

app/controllers/texts_controller.rb
class TextsController < ApplicationController

  before_filter :authorize

  def index
    work = Work.find(params[:work_id])
    @texts = work.texts.page(params[:page]).per(100)
    @sequence = params[:lineSequence]
  end

  def new
    @work = Work.find(params[:work_id])
    @text = @work.texts.find(params[:id])
    @previous_line = @text.previous_display_text(@work, @text.sequence)
    @current_line  = @text.display_string
    @next_line     = @text.next_display_text(@work, @text.sequence)
    @elements      = @work.elements.sort_by(&:name)
  end

  def create
    new_text = params['new_line']
    line = Text.find_by_id(params[:id]) #gives us the line we will insert after
    work_id = line.work_id #gives us the work id to use for selecting the right whitespace element
    sequence = line.sequence
    txt = Text.new(
      element_id: Element.find_by_id(params['character_name_dropdown']).id,
      work_id: work_id,
      content_text: new_text['content_text'],
      visibility: new_text['visibility'],
      operator_note: new_text['operator_note'],
      sequence: sequence + 1
    )
    if txt.save
      flash[:notice] = "New character line successfully added"
    else
      flash[:notice] = "New Line NOT added"
    end
    redirect_to :controller => 'texts', :action => 'index', :work_id => work_id, :page => params[:page], :lineSequence => sequence + 1
  end

  def edit
    @work = Work.find(params[:work_id])
    @text = @work.texts.find(params[:id])
    @previous_line = @text.previous_display_text(@work, @text.sequence)
    @current_line  = @text.display_string
    @next_line     = @text.next_display_text(@work, @text.sequence)
    @elements      = @work.elements.sort_by(&:name)
  end

  def update
    @text2 = Text.find(params[:id])
    message_params = params.require(:text).permit(:content_text, :visibility, :operator_note)
    if @text2.update_attributes(message_params)
      # Handle a successful update.
      flash[:notice] = "Text successfully updated"
      redirect_to :controller => 'texts', :action => 'index', :work_id => @text2.work_id.to_s, :page => params[:page], :lineSequence => params[:sequence]
    else
      flash[:notice] = "NOTICE: ERROR DURING UPDATE"
      redirect_to :controller => 'texts', :action => 'index', :work_id => @text2.work_id.to_s, :page => params[:page], :lineSequence => params[:sequence]
    end
  end

  def destroy
    lne = Text.find_by_id(params[:id]) #gives us the line
    wid = lne.work_id #gives us the work id to use for selecting the right whitespace element
    seqid = lne.sequence

    #remove the current line from the database
    lne.remove_from_list
    lne.destroy

    redirect_to :controller => 'texts', :action => 'index', :work_id => wid, :page => params[:page], :lineSequence => seqid
  end

  #********************************************************************
  #updates the visibility of a line when the visibility is toggled in editorview
  #******************************************************************
  def toggleVis
    @text2 = Text.find(params[:id])
    #sets the visibility from false to true
    if @text2.visibility == false
      if @text2.update_attributes(:visibility => true)
          render :json => 'true'
      else
          render :json => 'Failed to update the record to true'
      end
      #sets the visibility from true to false
    else
      if @text2.update_attributes(:visibility => false)
        render :json => 'true'
      else
        render :json => 'Failed to update record to false'
      end
    end
  end

end

app/helpers/texts_helper.rb
module TextsHelper
end

app/views/texts/_edit.html.erb
<div class="modal-dialog" id="unique">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      </br>
    </div>
    <div class="modal-body">
      <h2>Edit</h2>
      <div class="alert alert-success">
        <%= "#{@previous_line}" %>
      </div>
      <% provide(:title, "Edit contact") %>
      <div>
        <!--form for editing the content/settings of the line-->
        <%= form_for [@work, @text] do |f| %>

          <!-- toolbar -->
          <div class="btn-group" role="group">
            <button type="button" id="boldIt" class="btn btn-default">Uppercase</button>
            <button type="button" id="lowercaseIt" class="btn btn-default">Lowercase</button>
          </div>
          <br><br>

          <!-- operator note -->
          <div class='input-group'>
            <span class='input-group-addon'>Operator Note</span>
            <%= f.text_field :operator_note, class: 'form-control', placeholder: "placeholder text" %>
          </div>
          </br>
          <!-- content_text -->
          <div class='input-group'>
            <span class='input-group-addon'>Text</span>
            <%= f.text_area :content_text, class: 'form-control input-xlarge', rows: 4 %>
          </div>
          </br>
          <!-- character -->
          <div class='input-group'>
            <!--
            <span class='input-group-addon'>Character</span>
            <label class='form-control'><%= @text.element.name %></label>
            -->
          </div>

          <!-- element -->
          <div class='input-group'>
            <!--
            <p><%="Element: " + @text.element.element_type%></p>
            -->
          </div>

          <!-- the rest -->
          <div id="character-counter">
            <ul class="list-group">

              <li class="list-group-item">
                <%if @text.element.element_name.blank? %>
                  Element Type
                  <span class="badge"><%= @text.element.element_type %></span> 
                <%else%>
                  Character
                  <span class="badge"><%= @text.element.element_name %></span>
              <%end%>
              </li>

              <li class="list-group-item">
                Visibility
                <div class="pull-right">
                  <%= f.check_box :visibility %>
                </div>
              </li>

              <li class="list-group-item">
                <span class="badge"><%= @text.sequence %></span>
                Sequence Number
              </li>

              <li class="list-group-item">
                <span id="text_word_count" class="badge"><%= @text.content_text.length.to_s%></span>
                Characters
              </li>
            </ul>
          </div>

          <div class="alert alert-success">
            <%= "#{@next_line}" %>
          </div>
            <!--additional parameters for scrolling to line in editor after modal closes-->
            <%= hidden_field_tag 'page', params[:page]  %>
            <%= hidden_field_tag 'sequence', @text.sequence  %>

          <div class="modal-footer">
            <!-- button controls -->
            <div class="pull-right" role="group">
              <button type="button" class="btn btn-default" data-dismiss="modal">Discard</button>
              <button type="submit" class="btn btn-primary">Update</button>
            </div>

            <div class="pull-left" role="group">
              <%= link_to 'Delete This Line', work_text_path(:work_id => @work.id, :id => @text.id, :page => params[:page]), method: "delete", class: 'btn btn-danger' %>
            </div>
          </div>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/texts/_new.html.erb
<div class="modal-dialog" id="unique">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      </br>
    </div>
    <div class="modal-body">
      <h2>New Text</h2>
      <div class="alert alert-success">
        <%= "#{@current_line}" %>
      </div>
      <% provide(:title, "Edit contact") %>
      <div>
        <%= form_for :new_line, :url => work_texts_path(:work_id => @work.id, :id => @text.id), :method => "post" do |f| %>
          <div class="btn-group" role="group">
            <button type="button" id="boldIt" class="btn btn-default">Uppercase</button>
            <button type="button" id="lowercaseIt" class="btn btn-default">Lowercase</button>
          </div>
          <br></br>
          <div class='input-group'>
            <span class='input-group-addon'>Operator Note</span>
            <%= f.text_field :operator_note, class: 'form-control', placeholder: "placeholder text" %>
          </div>
          </br>
          <div class='input-group'>
            <%= label_tag 'content_text', 'Text', class: 'input-group-addon' %>
            <%= f.text_area :content_text, class: 'form-control input-xlarge', rows: 4 %>
          </div>
          <br />
          <div id="character-counter">
            <ul class="list-group">
              <li class="list-group-item">
                <span class="pull-right"><%= select_tag 'character_name_dropdown',
                  options_from_collection_for_select(@elements, 'id', 'name'),
                  class: 'btn btn-default btn-xs' %>
                </span>
                Element
              </li>
              <li class="list-group-item">
                Visibility
                <div class="pull-right">
                  <%= f.check_box :visibility, :checked => true %>
                </div>
                </li>
              <li class="list-group-item">
                <span id=text_word_count class="badge">0</span>
                Characters
              </li>
            </ul>
          </div>
            <!--additional parameters for scrolling to line in editor after modal closes-->
            <%= hidden_field_tag 'page', params[:page]  %>
            <%= hidden_field_tag 'sequence', @text.sequence  %>
          </br>
          <div class="alert alert-success">
            <%= "#{@next_line}" %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Discard</button>
            <button type="submit" class="btn btn-primary" >Save</button>
          </div>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/texts/edit.js.erb
$("#unique").remove();
$("#edit_modal").append("<%= escape_javascript(render :partial => 'texts/edit') %>");
$("#edit_modal").modal("show");

$("#text_visibility").bootstrapSwitch({size: 'mini'});

$('#text_content_text').keyup(function(){
 var element = document.getElementById('text_word_count');
 var len = document.getElementById('text_content_text').value.length;
 element.textContent = len;

  var max_characters = <%= @work.characters_per_line %>;
  console.log(max_characters);
  var cs = $(this).val().length;
    if(len > max_characters){
      $('#text_word_count').addClass('above_limit');
    }
    else{
      $('#text_word_count').removeClass('above_limit');
    }

});

//***********************************************
//used for bolding selected lines in the editorview
//***********************************************
$('#boldIt').click(function(){
  var textComponent = document.getElementById('text_content_text');
  var selectedText;
  // IE version
  if (document.selection != undefined){
    console.log('not ie')
    textComponent.focus();
    var sel = document.selection.createRange();
    selectedText = sel.text;
  }
  // Mozilla version
  else if (textComponent.selectionStart != undefined){
    var startPos = textComponent.selectionStart;
    var endPos = textComponent.selectionEnd;
    selectedText = textComponent.value.substring(startPos, endPos)
  }
  //bolds the text that is highlighted in the textarea
  $('textarea#text_content_text').val(
  $('textarea#text_content_text').val().substring(0, textComponent.selectionStart)
    + selectedText.toUpperCase()
    + $('textarea#text_content_text').val().substring(textComponent.selectionEnd)
  );
});

//***********************************************
//used for bolding selected lines in the editorview
//***********************************************
$('#lowercaseIt').click(function(){
  var textComponent = document.getElementById('text_content_text');
  var selectedText;
  // IE version
  if (document.selection != undefined){
    console.log('not ie')
    textComponent.focus();
    var sel = document.selection.createRange();
    selectedText = sel.text;
  }
  // Mozilla version
  else if (textComponent.selectionStart != undefined){
    var startPos = textComponent.selectionStart;
    var endPos = textComponent.selectionEnd;
    selectedText = textComponent.value.substring(startPos, endPos)
  }
  //bolds the text that is highlighted in the textarea
  $('textarea#text_content_text').val(
  $('textarea#text_content_text').val().substring(0, textComponent.selectionStart)
    + selectedText.toLowerCase()
    + $('textarea#text_content_text').val().substring(textComponent.selectionEnd)
  );
});

app/views/texts/index.html.erb
  <!--create loop for an array holding elements containing lines-->

  <h2 class="form-title">Lines available for editing</h2>
  <p id="notice"><%= notice %></p>
  <p>
    <%= link_to 'Back to Main', cast_index_path, :class => 'btn btn-primary', method: :get %>
  </p>

  <!--this is the view for showing all the contacts in the database-->
  <% if @texts.blank? %>
    <p>No lines to display.</p>
  <% else %>
    <%= paginate @texts %>

    <!--table showing all lines for the current script-->
    <table id="works" class='table'>
      <tr>
        <% %w{Sequence Character Type Text Visibility Notes Edit New}.each do |header_name| %>
          <th><%= header_name %></th>
        <% end %>
      </tr>

      <% @texts.each do |line| %>
          <% if line.sequence == @sequence.to_i %>
            <tr class="focus-here">
          <% else %>
            <tr>
          <% end %>
            <td><%= line.sequence %></td>
            <td><%= line.element_name %></td>
            <td><%= line.element_type %></td>
          <%if line.element_type == 'BLANKLINE'%>
            <td></td>
          <%else%>
            <td><%= line.content_text %></td>
          <%end%>
          <td>
            <% if line.visibility %>
              <span class='glyphicon visi visiTr glyphicon-eye-open' data-id="<%= line.id %>"></span>
            <% else %>
              <span class='glyphicon visi visiTr glyphicon-eye-close' data-id='<%= line.id %>'></span>
            <% end %>
          </td>
          <td><%= line.operator_note %></td>
          <!--link to edit specific this line-->
          <td><%= link_to 'EDIT', edit_work_text_path(work_id: line.work_id, id: line.id, page: params[:page], format: :js), :class => 'link-edit', :remote => true %></td>
          <td><%= link_to 'NEW', new_work_text_path(work_id: line.work_id, id: line.id, page: params[:page], format: :js), :class => 'link-edit', :remote => true %></td>
        </tr>
      <% end %>
    </table>
    <%= paginate @texts %>
  <% end %>

  <div id="edit_modal" class="modal fade">
  </div>
  <div id="new_modal" class="modal fade">
  </div>

app/views/texts/new.js.erb
$("#unique").remove();
$("#new_modal").append("<%= escape_javascript(render :partial => 'texts/new') %>");
$("#new_modal").modal("show");
$("#new_line_visibility").bootstrapSwitch({size: 'mini'});

$('#character_name_dropdown').on('change', function() {
  if($(this).find('option:selected').text() == "BLANKLINE") {
    $("#new_line_content_text").val("<br />");
    $("#new_line_content_text").prop("readonly", true);
    $("#new_line_visibility").bootstrapSwitch("state", true); 
    $("#new_line_visibility").bootstrapSwitch("readonly", true);
  }
  else {
    $("#new_line_content_text").prop("readonly", false);
    $("#new_line_visibility").bootstrapSwitch("state", false); 
    $("#new_line_visibility").bootstrapSwitch("readonly", false);
  }
});

$('#new_line_content_text').keyup(function(){
 var element = document.getElementById('text_word_count');
 var len = document.getElementById('new_line_content_text').value.length;
 element.textContent = len;

  var max_characters = <%= @work.characters_per_line %>;
  console.log(max_characters);
  var cs = $(this).val().length;
    if(len > max_characters){
      $('#text_word_count').addClass('above_limit');
    }
    else{
      $('#text_word_count').removeClass('above_limit');
    }
});

$('#boldIt').click(function(){
  var textComponent = document.getElementById('new_line_content_text');
  var selectedText;
  // IE version
  if (document.selection != undefined){
    console.log('not ie')
    textComponent.focus();
    var sel = document.selection.createRange();
    selectedText = sel.text;
  }
  // Mozilla version
  else if (textComponent.selectionStart != undefined){
    var startPos = textComponent.selectionStart;
    var endPos = textComponent.selectionEnd;
    selectedText = textComponent.value.substring(startPos, endPos)
  }
  //bolds the text that is highlighted in the textarea
  $('textarea#new_line_content_text').val(
  $('textarea#new_line_content_text').val().substring(0, textComponent.selectionStart)
    + selectedText.toUpperCase()
    + $('textarea#new_line_content_text').val().substring(textComponent.selectionEnd)
  );
});

$('#lowercaseIt').click(function(){
  var textComponent = document.getElementById('new_line_content_text');
  var selectedText;
  // IE version
  if (document.selection != undefined){
    console.log('not ie')
    textComponent.focus();
    var sel = document.selection.createRange();
    selectedText = sel.text;
  }
  // Mozilla version
  else if (textComponent.selectionStart != undefined){
    var startPos = textComponent.selectionStart;
    var endPos = textComponent.selectionEnd;
    selectedText = textComponent.value.substring(startPos, endPos)
  }
  //bolds the text that is highlighted in the textarea
  $('textarea#new_line_content_text').val(
  $('textarea#new_line_content_text').val().substring(0, textComponent.selectionStart)
    + selectedText.toLowerCase()
    + $('textarea#new_line_content_text').val().substring(textComponent.selectionEnd)
  );
});